version: '3.7'
services:
  app:
   container_name: golden-app
   build: .
   ports:
   - 8080:8080
   environment:
   - GOLDEN_DB_URL=localhost
   - GOLDEN_DB_NAME=goldenwaste
   - GOLDEN_DB_USERNAME=root
   - GOLDEN_DB_PASSWORD=DevOps2022
   - GOLDEN_DB_PORT=3306
   depends_on:
   - db
   networks:
   - goldenwaste-network
  
  db:
   container_name: goldenwastesqldb
   image: mysql
   environment:
   - MYSQL_ROOT_PASSWORD=DevOps2022
   - MYSQL_DATABASE=goldenwaste
   ports:
   - "3306:3306"
   volumes:
   - goldenwaste-mysql:var/lib/mysql
   - goldenwaste-mysql-config:/etc/mysql
   networks:
   - goldenwaste-network
   
volumes:
  goldenwaste-mysql:
  goldenwaste-mysql-config:

networks:
  goldenwaste-network:
    name: goldenwaste-network
    driver: bridge
    
    
